// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMpgFdHDHfhTmmnFyfua9WoDCB8WKY2Bk',
    appId: '1:266176476726:android:54d24b6114e6e6c279ca97',
    messagingSenderId: '266176476726',
    projectId: 'first-app-df271',
    storageBucket: 'first-app-df271.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrocOSSaS3zz4ouqQD09pYnHM_u6q8P8Y',
    appId: '1:266176476726:ios:b5a43cbae97a30f479ca97',
    messagingSenderId: '266176476726',
    projectId: 'first-app-df271',
    storageBucket: 'first-app-df271.firebasestorage.app',
    iosBundleId: 'com.example.governmentapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBopKwjWzeAePbmcORbzZWmA3zBBrUkMRI',
    appId: '1:266176476726:web:8d181776f19caa9679ca97',
    messagingSenderId: '266176476726',
    projectId: 'first-app-df271',
    authDomain: 'first-app-df271.firebaseapp.com',
    storageBucket: 'first-app-df271.firebasestorage.app',
    measurementId: 'G-K2REDDGZTH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrocOSSaS3zz4ouqQD09pYnHM_u6q8P8Y',
    appId: '1:266176476726:ios:b5a43cbae97a30f479ca97',
    messagingSenderId: '266176476726',
    projectId: 'first-app-df271',
    storageBucket: 'first-app-df271.firebasestorage.app',
    iosBundleId: 'com.example.governmentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBopKwjWzeAePbmcORbzZWmA3zBBrUkMRI',
    appId: '1:266176476726:web:95be8372be8e6bc579ca97',
    messagingSenderId: '266176476726',
    projectId: 'first-app-df271',
    authDomain: 'first-app-df271.firebaseapp.com',
    storageBucket: 'first-app-df271.firebasestorage.app',
    measurementId: 'G-3LLME9XJZQ',
  );

}